# Generated by Django 3.0.7 on 2020-07-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicuha', '0003_auto_20200702_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='begin_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
