# Generated by Django 3.0.7 on 2020-07-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicuha', '0004_auto_20200702_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemauser',
            name='wasted_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
