# Generated by Django 3.0.7 on 2020-07-04 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicuha', '0006_auto_20200704_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicuha.Hall', unique_for_date=('beginning_date', 'ending_date')),
        ),
    ]
