# Generated by Django 3.0.7 on 2020-07-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicuha', '0008_auto_20200704_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicuha.Hall', unique=True),
        ),
    ]
