# Generated by Django 3.0.7 on 2020-07-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicuha', '0013_auto_20200704_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicuha.Hall'),
        ),
    ]
